version: '3.9'
services:
  mp4-conversion-hub:
    image: qadraxdev/mp4-conversion-hub:latest
    cpus: 2
    mem_limit: 1g
    ports:
      - "3000:3000"
    volumes:
      - ./input:/input
      - ./output:/output
    env_file:
      - .env
    environment:
      TRUST_PROXY: ${TRUST_PROXY:-false}
      CONCURRENCY: ${CONCURRENCY:-1}
      VIDEO_ENCODING_PRESET: ${VIDEO_ENCODING_PRESET:-ultrafast}
      VIDEO_CRF: ${VIDEO_CRF:-28}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
      UPLOAD_RATE_LIMIT_MAX_ATTEMPTS: ${UPLOAD_RATE_LIMIT_MAX_ATTEMPTS:-5}
      UPLOAD_RATE_LIMIT_COOLDOWN_MINUTES: ${UPLOAD_RATE_LIMIT_COOLDOWN_MINUTES:-1}
      UPLOAD_SIZE_LIMIT_MB: ${UPLOAD_SIZE_LIMIT_MB:-3000}
      AUTH_RATE_LIMIT_MAX_ATTEMPTS: ${AUTH_RATE_LIMIT_MAX_ATTEMPTS:-3}
      AUTH_RATE_LIMIT_COOLDOWN_MINUTES: ${AUTH_RATE_LIMIT_COOLDOWN_MINUTES:-5}
      GENERAL_RATE_LIMIT_MAX_ATTEMPTS: ${GENERAL_RATE_LIMIT_MAX_ATTEMPTS:-100}
      GENERAL_RATE_LIMIT_COOLDOWN_MINUTES: ${GENERAL_RATE_LIMIT_COOLDOWN_MINUTES:-1}