name: Build and Release Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/app/Dockerfile
          push: true
          tags: |
            qadraxdev/mp4-conversion-hub:latest
            qadraxdev/mp4-conversion-hub:${{ github.event.release.tag_name }}

      - name: Save Docker image to tar
        run: |
          docker pull qadraxdev/mp4-conversion-hub:${{ github.event.release.tag_name }}
          docker save qadraxdev/mp4-conversion-hub:${{ github.event.release.tag_name }} | gzip > mp4-conversion-hub-${{ github.event.release.tag_name }}.tar.gz

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mp4-conversion-hub-${{ github.event.release.tag_name }}.tar.gz
            release-assets/docker-compose.yml
            release-assets/download-image.sh
            CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
