name: OSV Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  osv-scan:
    name: Scan root package-lock.json with OSV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OSV-Scanner
        run: |
          curl -sSfL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/

      - name: Run OSV-Scanner
        run: |
          osv-scanner --lockfile=package-lock.json
